# https://login.microsoftonline.com//microsoft.com/.well-known/openid-configuration
# RAW
# {
#     "token_endpoint": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token",
#     "token_endpoint_auth_methods_supported": [
#         "client_secret_post",
#         "private_key_jwt",
#         "client_secret_basic"
#     ],
#     "jwks_uri": "https://login.microsoftonline.com/common/discovery/keys",
#     "response_modes_supported": [
#         "query",
#         "fragment",
#         "form_post"
#     ],
#     "subject_types_supported": [
#         "pairwise"
#     ],
#     "id_token_signing_alg_values_supported": [
#         "RS256"
#     ],
#     "response_types_supported": [
#         "code",
#         "id_token",
#         "code id_token",
#         "token id_token",
#         "token"
#     ],
#     "scopes_supported": [
#         "openid"
#     ],
#     "issuer": "https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/",
#     "microsoft_multi_refresh_token": true,
#     "authorization_endpoint": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/authorize",
#     "device_authorization_endpoint": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/devicecode",
#     "http_logout_supported": true,
#     "frontchannel_logout_supported": true,
#     "end_session_endpoint": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/logout",
#     "claims_supported": [
#         "sub",
#         "iss",
#         "cloud_instance_name",
#         "cloud_instance_host_name",
#         "cloud_graph_host_name",
#         "msgraph_host",
#         "aud",
#         "exp",
#         "iat",
#         "auth_time",
#         "acr",
#         "amr",
#         "nonce",
#         "email",
#         "given_name",
#         "family_name",
#         "nickname"
#     ],
#     "check_session_iframe": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/checksession",
#     "userinfo_endpoint": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/openid/userinfo",
#     "kerberos_endpoint": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/kerberos",
#     "tenant_region_scope": "WW",
#     "tenant_region_sub_scope": "NA",
#     "cloud_instance_name": "microsoftonline.com",
#     "cloud_graph_host_name": "graph.windows.net",
#     "msgraph_host": "graph.microsoft.com",
#     "rbac_url": "https://pas.windows.net"
# }
openapi: '3.0.2'
info:
  title: Tenant Configuration Api
  version: '0.1'
servers:
- url: https://login.microsoftonline.com
components:
  schemas:
    openId:
      type: object
      properties:
        token_endpoint:
          type: string
        token_endpoint_auth_methods_supported:
          type: array
          items:
            type: string
        jwks_uri:
          type: string
        response_modes_supported:
          type: array
          items:
            type: string
        subject_types_supported:
          type: array
          items:
            type: string
        id_token_signing_alg_values_supported:
          type: array
          items:
            type: string
        response_types_supported:
          type: array
          items:
            type: string
        scopes_supported:
          type: array
          items:
            type: string
        issuer:
          type: string
        microsoft_multi_refresh_token:
          type: boolean
        authorization_endpoint:
          type: string
        device_authorization_endpoint:
          type: string
        http_logout_supported:
          type: boolean
        frontchannel_logout_supported:
          type: boolean
        end_session_endpoint:
          type: string
        claims_supported:
          type: array
          items:
            type: string
        check_session_iframe:
          type: string
        userinfo_endpoint:
          type: string
        kerberos_endpoint:
          type: string
        tenant_region_scope:
          type: string
        tenant_region_sub_scope:
          type: string
        cloud_instance_name:
          type: string
        cloud_graph_host_name:
          type: string
        msgraph_host:
          type: string
        rbac_url:
          type: string
  parameters:
    tenant-id:
      name: tenant-id
      in: path
      required: true
      schema:
        type: string
      description: The tenant ID or Domain

paths:
  /{tenant-id}/.well-known/openid-configuration:
    get:
      description: Get OpenID Configuration
      operationId: GetOpenIdConfiguration
      parameters:
      - $ref: '#/components/parameters/tenant-id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/openId'